//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAQuanLyNV_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCong
    {
        public string MaNV { get; set; }
        public string MaDA { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
    
        public virtual Duan Duan { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
